### PR TITLE
Add documentation for Home Manager

### PR DESCRIPTION
**Pull request by rycee**

### CODE REVIEW

**Comment by domenkozar** [comment]
@rycee this looks good, ready to merge?

**Comment by rycee** [comment]
@domenkozar Yeah, I think it is pretty done. The problem may be that the https://cachix.org/api/v1/install URL currently wouldn't return a version of cachix that supports HM deployments. So I think a new Cachix release would be needed before deploying these documentation updates.

**Comment by rycee** [comment]
Oh, and the `services.cachix-agent` module has not been merged to Home Manager yet, so the Flake example won't work right now. We can't really do the merge until the Cachix package in Nixpkgs unstable has been updated to a version that supports HM deploys 😕

**Comment by domenkozar** [comment]
Alright, we'll make a release soon and I'll ping you once it's ready.

**Comment by rycee** [comment]
Nice. Btw, how do I accept the CLA? And the CI/docs job seems to fail due to some unrelated problem?

About the HM module, the associated PR is https://github.com/nix-community/home-manager/pull/3380.

**Comment by domenkozar** [comment]
I'm fighting with poetry2nix to fix the build :(

**Comment by domenkozar** [comment]
Fixed CI, I need to fix CLA since the new version has a different behavior.

**Pull request merged**
